name: NodeJS with Webpack

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    - name: Read package.json
      uses: dutscher/read-package-json-endpoint-actions@v1.33.7
      id: package-json-endpoint

    - name: Show version number
      run: echo "Version Library -> ${{ steps.package-json-endpoint.outputs.endpoint }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ steps.package-json-endpoint.outputs.endpoint }}
        release_name: Release v${{ steps.package-json-endpoint.outputs.endpoint }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false
