name: NodeJS with Webpack

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  Build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/

    - name: Read node from package.json
      uses: culshaw/read-package-node-version-actions@v1
      id: package-node-version

    - name: Show node version number
      run: echo "Version is ${{ steps.package-node-version.outputs.version }}"

    - name: Publish to NPM
      run: |
        npm i
        npm ci
        npm publish --access=public
        curl -POST -U "${{secrets.USERNAME}}:${{secrets.PASSWORD}}" -H "Authorization: token ${{secrets.PAT_TOKEN}}"  -H "Accept: application/vnd.github.v3+json" -H "Content-Type: application/json" https://api.github.com/repos/MHW-EC/Lambda-Functions/dispatches --data '{"event_type": "Deploy lambdas for MHWLib v${{ steps.package-node-version.outputs.version }}"}'
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
